#!/bin/bash

echo "=== GUIA DE DEPLOY VERITAS RADIX ==="
echo ""

echo "1. SUBIR PARA O GITHUB:"
echo "cd '/home/felipe/Downloads/Veritas Radix-deploy-test'"
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit'"
echo "git remote add origin https://github.com/SEU_USUARIO/veritas-radix.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "2. DEPLOY FRONTEND (VERCEL):"
echo "- Acesse: https://vercel.com"
echo "- New Project > Selecione repositório"
echo "- Framework: Vite"
echo "- Build Command: npm run build"
echo "- Output Directory: build"
echo "- Adicione variáveis de ambiente:"
echo "  VITE_API_URL=https://seu-backend.onrender.com"
echo "  VITE_GOOGLE_AI_API_KEY=sua_chave"
echo "  VITE_OPENAI_API_KEY=sua_chave"
echo ""

echo "3. DEPLOY BACKEND (RENDER):"
echo "- Acesse: https://render.com"
echo "- New Web Service > Selecione repositório"
echo "- Root Directory: src/backend"
echo "- Build Command: pip install -r requirements.txt"
echo "- Start Command: gunicorn veritas_radix.wsgi:application"
echo "- Adicione PostgreSQL database"
echo "- Configure variáveis de ambiente no dashboard"
echo ""

echo "Arquivos criados:"
echo "- .gitignore"
echo "- .env.production (exemplo)"
echo "- vercel.json"
echo "- DEPLOY_GUIDE.md (guia completo)"
echo "- src/backend/Procfile"